module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'verse',
        'chapter',
        'ask',
        'daily',
        'journal',
        'search',
        'library',
        'auth',
        'share',
        'whatsapp',
        'shared',
        'db',
        'ci',
        'deps',
        'docs',
        'design',
      ],
    ],
    'subject-case': [0],
  },
};
